project:
  type: website
  output-dir: _site
  resources:
    - "_includes/"

website:
  title: "Alumni News & Tracking"
  description: "Stay connected with our community"
  
  navbar:
    background: primary
    search: true
    title: false
    logo: "ika.png"
    logo-alt: "IKA Unhas Jabodetabek"
    logo-height: "10000px"
    left:
      - href: index.qmd
        text: Beranda
      - href: news/index.qmd
        text: Kabar Alumni
      - href: alumni/index.qmd
        text: Portal Alumni
      - href: about.qmd
        text: Tentang
    right:
      - icon: instagram
        href: https://www.instagram.com/ika.unhas.jabodetabek/
      - icon: github
        href: https://github.com/yourusername/alumni-website
      - icon: envelope
        href: mailto:admin@alumni.org

  page-footer:
    left: "© 2025 Alumni Association"
    right: 
      - icon: envelope
        href: mailto:contact@alumni.org
      - icon: github
        href: https://github.com/himharis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    code-fold: true
    code-summary: "Show code"
    include-before-body: |
      <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>
      <script src="_includes/supabase-client.js"></script>

execute:
  freeze: auto